const BLUETOOTH_SCAN_LENGTH_SECONDS = 5;
const BLUETOOTH_PAIR_WAIT_LENGTH_SECONDS = 10;
const BLUETOOTH_CONNECT_WAIT_LENGTH_SECONDS = 5;
const BLUETOOTH_COOLDOWN_WAIT_SECONDS = 10;

module.exports = {BLUETOOTH_COOLDOWN_WAIT_SECONDS, BLUETOOTH_CONNECT_WAIT_LENGTH_SECONDS, BLUETOOTH_SCAN_LENGTH_SECONDS, BLUETOOTH_PAIR_WAIT_LENGTH_SECONDS}